addSbtPlugin("com.danieltrinh"   % "sbt-scalariform"     % "1.3.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"             % "0.6.4")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager" % "1.0.0-M5")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "1.1.1")
addSbtPlugin("io.spray"          % "sbt-revolver"        % "0.7.2")
